### PR TITLE
Added stdio include

### PR DESCRIPTION
**Pull request by Scellow**
I wasn't able to compile it using MinGW 

```
 error: 'EOF' was not declared in this scope
             while (stream.peek() != EOF)
```

### CODE REVIEW

**Comment by texus** [comment]
Thanks, apparently testing on 5 different compilers wan't enough to get standard compliant code 😄

Could you change it to <cstdio> though? Then I'll merge it.

**Comment by Scellow** [comment]
Hmm i'm not sure if I understood what you mean ^^, what do you want me to change?

**Comment by texus** [comment]
I forgot one word in that sentence :)
It should have been "Could you change it to <cstdio> though?"
Because stdio.h is the c library instead of the c++ one. It shouldn't make any difference, it is just to be consistent with other includes.

**Comment by Scellow** [comment]
Ohh, right! i'll do it now

**Comment by Scellow** [comment]
Done :)

**Pull request merged**
