### PR TITLE
Update for SFML 2.4

### PR DESCRIPTION
**Pull request by Cmdu76**
I used SFML_VERSION_MAJOR and SFML_VERSION_MINOR to ensure that the library will be usable for SFML 2.4 and older versions.

### CODE REVIEW

**Comment by texus** [comment]
Thanks for contributing.

There are two reasons why I can't pull this though:
- The code won't work for a version like 3.0, the conditional if check should be "major > 2 or (major == 2 and minor >= 4)"
- You used tabs instead of spaces in some lines

Could you perhaps patch these things?

**Comment by Cmdu76** [comment]
Just a question about my commits and newer commits, are they automatically applied to the build downloadable on the website with travis and appveyor ? Or I have to build it myself ?

**Comment by texus** [comment]
You have to build the github version yourself, the downloads on the website are not updated.

**Comment by Cmdu76** [comment]
Thank you for your answer and being so reactive !

**Pull request merged**
